include README.md
include LICENSE

# Include configs, assets, and metadata
recursive-include satmvs *.json *.yaml *.yml
recursive-include satmvs/config *
recursive-include satmvs/assets *

# Include model checkpoints (e.g., *.ckpt)
recursive-include checkpoints *

# Include example data (e.g., infos/, Generate_orders/)
recursive-include infos *
recursive-include Generate_orders *
